project_name: checksum
before:
  hooks:
    - "echo 'disabled hooks"
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  binary: checksum
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: 'SNAPSHOT-{{ printf "%.7s" .Commit }}'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
